/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import DAO.CategoriaDAO;
import DAO.ProdutoDAO;
import bin.Categoria;
import bin.Produto;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Usuario
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        initProduto();
        jBoxProd();
        readJTableProd();
        initCategoria();
        readJTableCat();
    }

    private void initCategoria() {
        txt_cat_nome.setEnabled(false);
        txt_cat_descricao.setEnabled(false);
        btn_cat_salvar.setEnabled(false);
        btn_cat_cancelar.setEnabled(false);
        txt_cat_nome.setText("");
        txt_cat_descricao.setText("");
        btn_cat_editar.setEnabled(false);
        btn_cat_remover.setEnabled(false);
    }
    
    private void initProduto() {
        txt_prod_nome.setEnabled(false);
        txt_prod_descricao.setEnabled(false);
        txt_prod_quantidade.setEnabled(false);
        txt_prod_preco.setEnabled(false);
        btn_prod_salvar.setEnabled(false);
        btn_prod_cancelar.setEnabled(false);
        jbox_prod.setEnabled(false);
        btn_prod_editar.setEnabled(false);
        btn_prod_remover.setEnabled(false);
        txt_prod_nome.setText("");
        txt_prod_descricao.setText("");
        txt_prod_quantidade.setText("");
        txt_prod_preco.setText("");
    }
    
    public void readJTableCat() {
        DefaultTableModel model = (DefaultTableModel) tbl_categoria.getModel();
        model.setNumRows(0);
        CategoriaDAO catdao = new CategoriaDAO();
        Iterator<Categoria> iterator = catdao.read();
        while(iterator.hasNext()) {
            Categoria categoria = iterator.next();
            model.addRow(new Object[]{
               categoria.getId(),
               categoria.getName(),
               categoria.getDescription()
            });
            
        }
    }
    
    public void readJTableProd() {
        DefaultTableModel model = (DefaultTableModel) tbl_produto.getModel();
        model.setNumRows(0);
        ProdutoDAO proddao = new ProdutoDAO();
        Iterator<Produto> iterator = proddao.read();
        while(iterator.hasNext()) {
            Produto produto = iterator.next();
            model.addRow(new Object[]{
               produto.getId(),
               produto.getName(),
               produto.getDescription(),
               produto.getQuantity(),
               produto.getPrice(),
               produto.getCategory()
            });
            
        }
    }
    
    public void jBoxProd() {
        jbox_prod.removeAllItems();
        CategoriaDAO catdao = new CategoriaDAO();
        Iterator iterator = catdao.read();
        while(iterator.hasNext()) {
            
            jbox_prod.addItem(iterator.next());
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_prod_nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_prod_descricao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_prod_quantidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jbox_prod = new javax.swing.JComboBox<>();
        btn_prod_cancelar = new javax.swing.JButton();
        btn_prod_salvar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_prod_preco = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_produto = new javax.swing.JTable();
        btn_prod_cadastrar = new javax.swing.JButton();
        btn_prod_remover = new javax.swing.JButton();
        btn_prod_editar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_cat_editar = new javax.swing.JButton();
        btn_cat_cadastrar = new javax.swing.JButton();
        btn_cat_remover = new javax.swing.JButton();
        cat_panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_cat_nome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_cat_descricao = new javax.swing.JTextField();
        btn_cat_cancelar = new javax.swing.JButton();
        btn_cat_salvar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_categoria = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Produto"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nome:*");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Descrição:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Quantidade:*");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Categoria:*");

        btn_prod_cancelar.setText("Cancelar");
        btn_prod_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prod_cancelarActionPerformed(evt);
            }
        });

        btn_prod_salvar.setText("Salvar");
        btn_prod_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prod_salvarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Preço:*");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_prod_descricao)
                            .addComponent(txt_prod_nome)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_prod_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_prod_preco, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbox_prod, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_prod_salvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_prod_cancelar)))
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_prod_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_prod_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_prod_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jbox_prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_prod_preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_prod_salvar)
                    .addComponent(btn_prod_cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_produto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Descrição", "Quantidade", "Preço", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_produto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_produtoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_produto);

        btn_prod_cadastrar.setText("Cadastrar");
        btn_prod_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prod_cadastrarActionPerformed(evt);
            }
        });

        btn_prod_remover.setText("Remover");
        btn_prod_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prod_removerActionPerformed(evt);
            }
        });

        btn_prod_editar.setText("Editar");
        btn_prod_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prod_editarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_prod_cadastrar)
                                .addGap(11, 11, 11)
                                .addComponent(btn_prod_editar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_prod_remover)))
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_prod_cadastrar)
                    .addComponent(btn_prod_remover)
                    .addComponent(btn_prod_editar))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Produtos", jPanel1);

        btn_cat_editar.setText("Editar");
        btn_cat_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cat_editarActionPerformed(evt);
            }
        });

        btn_cat_cadastrar.setText("Cadastrar");
        btn_cat_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cat_cadastrarActionPerformed(evt);
            }
        });

        btn_cat_remover.setText("Remover");
        btn_cat_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cat_removerActionPerformed(evt);
            }
        });

        cat_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Categoria"));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Nome:*");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Descrição:");

        btn_cat_cancelar.setText("Cancelar");
        btn_cat_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cat_cancelarActionPerformed(evt);
            }
        });

        btn_cat_salvar.setText("Salvar");
        btn_cat_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cat_salvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cat_panelLayout = new javax.swing.GroupLayout(cat_panel);
        cat_panel.setLayout(cat_panelLayout);
        cat_panelLayout.setHorizontalGroup(
            cat_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cat_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cat_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cat_panelLayout.createSequentialGroup()
                        .addGroup(cat_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cat_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cat_panelLayout.createSequentialGroup()
                                .addComponent(txt_cat_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_cat_descricao)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cat_panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_cat_salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_cat_cancelar)))
                .addContainerGap())
        );
        cat_panelLayout.setVerticalGroup(
            cat_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cat_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cat_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_cat_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cat_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_cat_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cat_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cat_cancelar)
                    .addComponent(btn_cat_salvar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_categoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_categoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_categoriaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_categoria);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cat_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_cat_cadastrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_cat_editar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_cat_remover))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cat_editar)
                    .addComponent(btn_cat_cadastrar)
                    .addComponent(btn_cat_remover))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cat_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Categoria", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_prod_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prod_removerActionPerformed
        if(tbl_produto.getSelectedRow() != -1) {
            
            Produto produto = new Produto();
            ProdutoDAO proddao = new ProdutoDAO();

            produto.setId((int)tbl_produto.getValueAt(tbl_produto.getSelectedRow(), 0));
            proddao.delete(produto);

            initProduto();
            btn_prod_cadastrar.setEnabled(true);
            readJTableProd();
        } 
    }//GEN-LAST:event_btn_prod_removerActionPerformed

    private void btn_cat_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cat_cadastrarActionPerformed
        
        txt_cat_nome.setEnabled(true);
        txt_cat_descricao.setEnabled(true);
        btn_cat_salvar.setEnabled(true);
        btn_cat_cancelar.setEnabled(true);
        
    }//GEN-LAST:event_btn_cat_cadastrarActionPerformed

    private void btn_cat_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cat_cancelarActionPerformed
        initCategoria();
    }//GEN-LAST:event_btn_cat_cancelarActionPerformed

    private void btn_cat_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cat_salvarActionPerformed
        
        Categoria categoria = new Categoria();
        CategoriaDAO catdao = new CategoriaDAO();
        
        
        categoria.setName(txt_cat_nome.getText());
        categoria.setDescription(txt_cat_descricao.getText());
        catdao.insert(categoria);
        
        initCategoria();
        readJTableCat();
        jBoxProd();
    }//GEN-LAST:event_btn_cat_salvarActionPerformed

    private void btn_cat_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cat_removerActionPerformed
        
        if(tbl_categoria.getSelectedRow() != -1) {
            Categoria categoria = new Categoria();
            CategoriaDAO catdao = new CategoriaDAO();

            categoria.setId((int)tbl_categoria.getValueAt(tbl_categoria.getSelectedRow(), 0));
            catdao.delete(categoria);

            initCategoria();
            btn_cat_cadastrar.setEnabled(true);
            readJTableCat();
            jBoxProd();
        } 
        
        
    }//GEN-LAST:event_btn_cat_removerActionPerformed

    private void btn_cat_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cat_editarActionPerformed
        
        if(tbl_categoria.getSelectedRow() != -1) {
            Categoria categoria = new Categoria();
            CategoriaDAO catdao = new CategoriaDAO();

            categoria.setName(txt_cat_nome.getText());
            categoria.setDescription(txt_cat_descricao.getText());
            categoria.setId((int)tbl_categoria.getValueAt(tbl_categoria.getSelectedRow(), 0));
            catdao.update(categoria);

            initCategoria();
            btn_cat_cadastrar.setEnabled(true);
            readJTableCat();
            jBoxProd();
        } 
        
        
    }//GEN-LAST:event_btn_cat_editarActionPerformed

    private void tbl_categoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_categoriaMouseClicked

        if(tbl_categoria.getSelectedRow() != -1) {
            btn_cat_cadastrar.setEnabled(false);
            btn_cat_editar.setEnabled(true);
            btn_cat_remover.setEnabled(true);
            
            txt_cat_nome.setText(tbl_categoria.getValueAt(tbl_categoria.getSelectedRow(), 1).toString());
            txt_cat_descricao.setText(tbl_categoria.getValueAt(tbl_categoria.getSelectedRow(), 2).toString());
            
            txt_cat_nome.setEnabled(true);
            txt_cat_descricao.setEnabled(true);
        } 

    }//GEN-LAST:event_tbl_categoriaMouseClicked

    private void btn_prod_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prod_cancelarActionPerformed
        initProduto();
    }//GEN-LAST:event_btn_prod_cancelarActionPerformed

    private void btn_prod_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prod_cadastrarActionPerformed
        txt_prod_nome.setEnabled(true);
        txt_prod_descricao.setEnabled(true);
        txt_prod_quantidade.setEnabled(true);
        txt_prod_preco.setEnabled(true);
        btn_prod_salvar.setEnabled(true);
        btn_prod_cancelar.setEnabled(true);
        jbox_prod.setEnabled(true);
    }//GEN-LAST:event_btn_prod_cadastrarActionPerformed

    private void btn_prod_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prod_salvarActionPerformed
        Produto produto = new Produto();
        Categoria jbox = (Categoria) jbox_prod.getSelectedItem();
        ProdutoDAO proddao = new ProdutoDAO();
        
        produto.setName(txt_prod_nome.getText());
        produto.setDescription(txt_prod_descricao.getText());
        produto.setQuantity(Integer.parseInt(txt_prod_quantidade.getText()));
        produto.setPrice(Double.parseDouble(txt_prod_preco.getText()));
        produto.setCategory(jbox.getName());
        produto.setCategoryId(jbox.getId());
        
        proddao.insert(produto);
        initProduto();
        readJTableProd();
    }//GEN-LAST:event_btn_prod_salvarActionPerformed

    private void tbl_produtoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_produtoMouseClicked
        
        if(tbl_produto.getSelectedRow() != -1) {
            btn_prod_cadastrar.setEnabled(false);
            btn_prod_editar.setEnabled(true);
            btn_prod_remover.setEnabled(true);
            CategoriaDAO catdao = new CategoriaDAO();
            
            txt_prod_nome.setText(tbl_produto.getValueAt(tbl_produto.getSelectedRow(), 1).toString());
            txt_prod_descricao.setText(tbl_produto.getValueAt(tbl_produto.getSelectedRow(), 2).toString());
            txt_prod_quantidade.setText(tbl_produto.getValueAt(tbl_produto.getSelectedRow(), 3).toString());
            txt_prod_preco.setText(tbl_produto.getValueAt(tbl_produto.getSelectedRow(), 4).toString());
            jbox_prod.setSelectedItem(catdao.retornaCategoria(tbl_produto.getValueAt(tbl_produto.getSelectedRow(), 5).toString()));
            txt_prod_nome.setEnabled(true);
            txt_prod_descricao.setEnabled(true);
            txt_prod_quantidade.setEnabled(true);
            txt_prod_preco.setEnabled(true);
            jbox_prod.setEnabled(true);
        } 
        
    }//GEN-LAST:event_tbl_produtoMouseClicked

    private void btn_prod_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prod_editarActionPerformed
        Produto produto = new Produto();
        Categoria jbox = (Categoria) jbox_prod.getSelectedItem();
        ProdutoDAO proddao = new ProdutoDAO();
        
        produto.setName(txt_prod_nome.getText());
        produto.setDescription(txt_prod_descricao.getText());
        produto.setQuantity(Integer.parseInt(txt_prod_quantidade.getText()));
        produto.setPrice(Double.parseDouble(txt_prod_preco.getText()));
        produto.setCategory(jbox.getName());
        produto.setCategoryId(jbox.getId());
        produto.setId((int)tbl_produto.getValueAt(tbl_produto.getSelectedRow(), 0));
        
        proddao.update(produto);
        initProduto();
        btn_prod_cadastrar.setEnabled(true);
        readJTableProd();
    }//GEN-LAST:event_btn_prod_editarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cat_cadastrar;
    private javax.swing.JButton btn_cat_cancelar;
    private javax.swing.JButton btn_cat_editar;
    private javax.swing.JButton btn_cat_remover;
    private javax.swing.JButton btn_cat_salvar;
    private javax.swing.JButton btn_prod_cadastrar;
    private javax.swing.JButton btn_prod_cancelar;
    private javax.swing.JButton btn_prod_editar;
    private javax.swing.JButton btn_prod_remover;
    private javax.swing.JButton btn_prod_salvar;
    private javax.swing.JPanel cat_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<Object> jbox_prod;
    private javax.swing.JTable tbl_categoria;
    private javax.swing.JTable tbl_produto;
    private javax.swing.JTextField txt_cat_descricao;
    private javax.swing.JTextField txt_cat_nome;
    private javax.swing.JTextField txt_prod_descricao;
    private javax.swing.JTextField txt_prod_nome;
    private javax.swing.JTextField txt_prod_preco;
    private javax.swing.JTextField txt_prod_quantidade;
    // End of variables declaration//GEN-END:variables
}
